/** Short discovery descriptions. Detailed contracts remain available through director_help. */
export const toolSummaries: Record<string, string> = {
    director_read: 'Read current scene creationMode (geometry includes a complete six-shape working palette), revision, IDs, duration/fps/aspect, cuts and production notes. Default entity summaries include color and reference image ID; ids + details:true returns selected full entities. resourceId inspects an imported model. No image/model bytes. Reuse the automatic task snapshot unless details or a fresh revision are needed.',
    director_assets: 'Search only the needed built-in models by query, queries:[names], exact ids or type filters. Empty input returns no catalog. Default 8 matches; found:false and missingQueries/missingIds mean no match. Do not scan all pages before building. Geometry mode uses the six IDs in director_read.geometry directly, no discovery needed. Request details only for unknown parameters.',
    director_motions: 'Find humanoid motions by query. source=user searches the local user library (paged); omitted/builtin searches built-ins. Use returned id in {operation:"motion",id:actorId,asset:presetId,time:0,duration:sceneSeconds}; omitted duration uses source default. User motions require complete mapping; sources embed in project. Humans/crowds only.',
    director_apply: 'Edit the current scene in place; no new project or scene is needed. Commit 1-100 operations atomically with current revision and unique requestId; undoable. Normal edits commit directly. Invalid input rolls back the batch. add:{asset,id?,name?,position?,patch?}; omit kind for built-ins/camera, kind is only for imported resources. update:{id,patch}; remove:{id}; project:{patch:{duration,fps,aspect,name,room,zones,creationMode,referenceLabels}}; cuts:{value:[{time:0,cameraId}]} (replaces timeline). motion:{id,asset:presetId,time:0,duration:seconds}. Same-batch add IDs may be used by following motions/cuts. project.referenceLabels toggles actor/crowd/capsule name labels in camera preview and exported reference video (default false). Entity patch supports color:"#RRGGBB", position/rotation/scale, path:{smooth:false,points:[{time,position:[x,y,z]}]}, clips:[{id,action,start,end,speed:1}]. Geometry values use the catalog parameterPatchField. camera shallow-merges e.g. {focal:50,target:[0,1.2,0]}; arrays and other nested objects replace wholly, read existing data before replacing. notes uses value:{fixedPrompt:"",sceneReferenceIds:[],notes:[{id,start,end,actorId:"",story:"",emotion:"",dialogue:"",action:""}]}; actorId empty or existing actor. Optional production.promptText stores the complete scene video-generation prompt. Preserve existing promptText when editing notes; use full production value, not patch. Unknown formats may use preview:true; preview creates no objects. Commit returned previewId with unchanged revision + NEW requestId, omitting operations. A stale preview needs revalidation. Keep locked entities and concurrent user changes. camera-motion and lighting-preset operations generate editable cinematography/environment presets; camera.effects adds animated lens/framing/shake/distortion, project.lighting and light-* assets add lighting. Query director_help for these parameters only when needed. camera.targetPath animates world look-at points independently using {smooth,points:[{time,position}]}; query help for zones/aim details. For imported rig/clips, handBinding, contactAnchors, floors, structureLink, resource edits and replace-prop, query director_help(names:["director_apply"]) only when needed.',
    director_scene: 'Default to editing the CURRENT scene with director_apply. Only create/copy/continue when the user asks for a separate scene, alternative or continuation; rooms along a continuous shot stay in one scene. Manage independent scenes, separate from camera cuts. list/read are queries. Mutations use revision + requestId. create(name,template?,newSceneId?) and copy(sceneId?,name) select the new scene; switch(sceneId) changes active scene. continue(name) creates a scene from ACTIVE scene last output frame, preserving original scene. Read director_continuity for predecessor history. rename/reorder/remove also supported; query help for details.',
    director_continuity: 'Read saved predecessor story and actual last-frame positions/poses, paged by offset/limit; follow nextOffset when all objects are needed. Source may since have changed; this is a frozen snapshot. director_spatial reads the current live scene instead.',
    director_spatial: 'Sample actual positions, bounds and camera framing at time. Optional ids returns only those entities (including crowd members); all scene objects still participate in occlusion. objects.zoneIds identifies named regions containing each current origin; zones are returned with bounds/connections. cameraId:"program" follows cuts; otherwise use an existing camera ID. occlusionKeys:["entity:ID"] requests ray samples. AABB overlap is approximate; sampled visibility never proves whole-scene correctness.',
    director_scan: 'Optional interval inspection: start/end/sampleFps and targetKey:"entity:ID" or "all-people", optional cameraId and occlusion. Returns jobId. Approximate samples; not required for every draft. director_job checks progress.',
    director_nodes: 'Inspect source/instance node hierarchy and real node bounds for an imported entityId. Optional time/path/query/offset/limit. Advanced: use only when editing model internals.',
    director_path_surface: 'Check a moving entityId route against surfaces; optional surfaceId/clearance/tolerance. Use after stairs/platform changes when route height matters. Does not edit or automatically find a route.',
    director_stride: 'Advanced read-only humanoid stride estimate for entityId + retarget clipId. Requires supported loaded skeleton; query help before applying locomotion calibration. Not needed for ordinary blocking.',
    director_view: 'Set preview time, optional cameraId (program or existing ID) and selected entityId. Does not change the project or cut timeline.',
    director_history: 'Undo/redo one batch with current revision and action:"undo"|"redo". Respects normal editor history.',
    director_export: 'Export kind:project|screenshot|video|bundle to local save flow. Video uses program cuts and project fps, optional start/end/size (640,1280,1920 long edge). Returns jobId for long work. save-requested means dialog requested, not disk save confirmed. No arbitrary filesystem paths.',
    director_job: 'Read job status/result by id; optional cancel:true. Do not repeatedly poll a running job without waiting.',
};

/** Only shorten prose, never change validation constraints. */
export function conciseSchema(value: unknown): unknown {
    if (Array.isArray(value)) return value.map(conciseSchema);
    if (!value || typeof value !== 'object') return value;
    return Object.fromEntries(Object.entries(value).filter(([key, v]) => key !== 'description' || typeof v !== 'string' || v.length <= 240)
        .map(([key, v]) => [key, conciseSchema(v)]));
}
